security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: apiToken

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

    password_hashers:
        App\Entity\User: plaintext