services:
  api_test:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lead-api-api_test
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=test
    depends_on:
      - mysql
      - redis
    networks:
      - default

  nginx_test:
    image: nginx:alpine
    container_name: lead-api-nginx_test
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default_test.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_test
    networks:
      - default
